name: Continuous Integration
on: [push]

jobs:
  build:
    name: Build and test
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Dotnet build
      run: dotnet build --configuration Release

    - name: Dotnet test
      run: dotnet test

    - name: Typescript install
      run: npm ci
      working-directory: ./DotnetTemplate.Web

    - name: Typescript build
      run: npm run build 
      working-directory: ./DotnetTemplate.Web

    - name: Typescript test
      run: npm run test
      working-directory: ./DotnetTemplate.Web

  docker:
    name: Build and push docker images
    needs: "build"
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Build Docker image
      run: docker build --tag pilavid/dotnettemplate .
    
    - name: Login to Docker Hub
      run: docker login -u pilavid -p ${{ secrets.DOCKERHUB_PASSWORD }}

    - name: Push Docker image
      run: docker push pilavid/dotnettemplate
  
  azure:
    name: Deploy to Azure
    needs: "docker"
    runs-on: ubuntu-latest
    steps:
    - name: WebHook to deploy into Azure
      run: curl -X POST "${{ secrets.AZURE_WEBHOOK }}"